version: "3"


services:

  db:
    image: postgres:latest
    env_file:
      - keys.txt
    ports:
      - "5432:5432"
    restart: always

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always