# Generated by Django 3.2.5 on 2021-07-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Событие')),
                ('start_event', models.DateTimeField()),
                ('end_event', models.DateTimeField()),
                ('notification', models.CharField(blank=True, choices=[('1HOUR', 'За час'), ('2HOUR', 'За два часа'), ('4HOUR', 'За 4 часа'), ('DAY', 'За день'), ('WEEK', 'За неделю')], db_index=True, max_length=30, null=True, verbose_name='Напоминание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
